Repository Automattic/Co-Authors-Plus, pull requests merged in 2023-08, with the labels that each got.

#973 check get_current_screen exists
  co-authors-plus.php
Labels: Type: bug

#979 CI: Update integration tests environments
  .github/workflows/integrate.yml
Labels: Type: maintenance

#976 975-verification with isset before using properties
  template-tags.php
Labels: Type: bug, Status: needs testing

#980 CLI: Add Behat functional tests
  behat.yml
  composer.json
  features/create-guest-author.feature
  features/rename-coauthor.feature
  features/testing.feature
  php/class-wp-cli.php
  tests/Behat/FeatureContext.php
Labels: Type: maintenance

#984 i18n: Add text domain header
  co-authors-plus.php
Labels: Type: bug

#985 Create LICENSE file
  LICENSE
Labels: Type: maintenance

#986 Refresh plugin headers
  co-authors-plus.php
Labels: Type: maintenance

#981 3.5.14
  CHANGELOG.md
  README.md
  co-authors-plus.php
  readme.txt
Labels: Type: maintenance

#989 Release 3.5.15
  CHANGELOG.md
  README.md
  co-authors-plus.php
  readme.txt
Labels: Type: maintenance
