Repository Automattic/Co-Authors-Plus, pull requests merged in 2023-07, with the labels that each got.

#942 Guest Authors: Add labels property
  php/class-coauthors-guest-authors.php
Labels: maintenance

#946 Workflows: Fix runner image and matrix
  .github/workflows/integrate.yml
Labels: Type: maintenance

#947 Define dynamic guest_authors property
  co-authors-plus.php
Labels: Type: maintenance

#948 CI: Split out CS and update integration tests workflow
  .distignore
  .github/workflows/cs-lint.yml
  .github/workflows/integrate.yml
  .gitignore
  .phpcs.xml.dist
  phpunit.xml.dist
Labels: Type: maintenance

#949 Improve tests setup
  .github/workflows/integrate.yml
  .gitignore
  bin/install-wp-tests.sh
  composer.json
  php/class-coauthors-endpoint.php
  php/class-coauthors-guest-authors.php
  phpunit.xml.dist
  tests/bootstrap.php
  tests/coauthorsplus-testcase.php
  tests/test-author-queried-object.php
  tests/test-author-queries.php
  tests/test-coauthors-endpoint.php
  tests/test-coauthors-guest-authors.php
  tests/test-coauthors-plus.php
  tests/test-manage-coauthors.php
  tests/test-template-tags.php
Labels: Type: maintenance

#951 Add .gitattributes file
  .gitattributes
Labels: Type: maintenance

#830 Hide deprecated social media links
  php/class-coauthors-guest-authors.php
  tests/test-coauthors-guest-authors.php
Labels: Type: enhancement, Priority: low, Status: needs review

#926 Fixes CoAuthors Plus & Elementor Archive Pages conflict. #905
  co-authors-plus.php
Labels: Type: bug, Status: needs testing

#957 Update README.md
  README.md
Labels: Type: documentation

#960 Fix avatar id collision between user id and guest-author post type
  co-authors-plus.php
Labels: Type: bug

#959 Issue#958/ unable to change avatar images sizes
  co-authors-plus.php
  css/co-authors-plus.css
Labels: Type: bug

#961 Add i18n string for PluginDocumentSettingPanel title
  build/index.asset.php
  build/index.js
  src/index.js
Labels: Type: bug

#963 Improve I18n strings
  .phpcs.xml.dist
  co-authors-plus.php
  languages/co-authors-plus.pot
  php/class-coauthors-endpoint.php
  php/class-coauthors-guest-authors.php
  php/class-wp-cli.php
  php/integrations/yoast.php
  template-tags.php
  tests/test-coauthors-guest-authors.php
Labels: Type: bug

#964 Fix notification to post co-authors
  co-authors-plus.php
Labels: Type: bug

#965 UI: Fix admin headings
  php/class-coauthors-guest-authors.php
Labels: Type: bug

#670 Refreshing meta box nonce after re-authenticating following a wp_auth_check()
  co-authors-plus.php
Labels: Type: bug, Status: needs testing

#966 Author archive: ensure queried object ID is an int
  co-authors-plus.php
Labels: Type: bug

#939 Ensure 'nickname' is created to prevent is_author() PHP notice with Guest Author
  php/class-coauthors-guest-authors.php
Labels: Type: bug, Status: needs testing

#967 Tests: Add previously deleted test back in
  tests/test-author-queried-object.php
Labels: Type: maintenance

#968 Release 3.5.12
  CHANGELOG.md
  README.md
  co-authors-plus.php
  readme.txt
Labels: Type: maintenance

#970 Revert "Fixes CoAuthors Plus & Elementor Archive Pages conflict"
  co-authors-plus.php
Labels: Type: bug

#971 3.5.13
  CHANGELOG.md
  README.md
  co-authors-plus.php
  readme.txt
Labels: Type: maintenance

#972 Docs: Add GaryJones as contributor
  readme.txt
Labels: Type: maintenance
