Repository Automattic/Co-Authors-Plus, pull requests merged in 2024-04, with the labels that each got.

#997 Blocks for Co-Authors
  README.md
  build/blocks-store/index.asset.php
  build/blocks-store/index.js
  build/blocks/block-coauthor-avatar/block.json
  build/blocks/block-coauthor-avatar/index.asset.php
  build/blocks/block-coauthor-avatar/index.js
  build/blocks/block-coauthor-avatar/style-index.css
  build/blocks/block-coauthor-description/block.json
  build/blocks/block-coauthor-description/index.asset.php
  build/blocks/block-coauthor-description/index.css
  build/blocks/block-coauthor-description/index.js
  build/blocks/block-coauthor-image/block.json
  build/blocks/block-coauthor-image/index.asset.php
  build/blocks/block-coauthor-image/index.js
  build/blocks/block-coauthor-image/style-index.css
  build/blocks/block-coauthor-name/block.json
  build/blocks/block-coauthor-name/index.asset.php
  build/blocks/block-coauthor-name/index.js
  build/blocks/block-coauthors/block.json
  build/blocks/block-coauthors/index.asset.php
  build/blocks/block-coauthors/index.js
  build/blocks/block-coauthors/style-index.css
  co-authors-plus.php
  package-lock.json
  package.json
  php/api/endpoints/class-coauthors-controller.php
  php/blocks/block-coauthor-avatar/class-block-coauthor-avatar.php
  php/blocks/block-coauthor-description/class-block-coauthor-description.php
  php/blocks/block-coauthor-image/class-block-coauthor-image.php
  php/blocks/block-coauthor-name/class-block-coauthor-name.php
  php/blocks/block-coauthors/class-block-coauthors.php
  php/blocks/class-blocks.php
  php/blocks/templating/class-templating.php
  src/blocks-store/index.js
  src/blocks/block-coauthor-avatar/block.json
  src/blocks/block-coauthor-avatar/edit.js
  src/blocks/block-coauthor-avatar/index.js
  src/blocks/block-coauthor-avatar/style.css
  src/blocks/block-coauthor-description/block.json
  src/blocks/block-coauthor-description/edit.js
  src/blocks/block-coauthor-description/editor.css
  src/blocks/block-coauthor-description/index.js
  src/blocks/block-coauthor-image/block.json
  src/blocks/block-coauthor-image/dimension-controls.js
  src/blocks/block-coauthor-image/edit.js
  src/blocks/block-coauthor-image/index.js
  src/blocks/block-coauthor-image/style.css
  src/blocks/block-coauthor-image/utils.js
  src/blocks/block-coauthor-name/block.json
  src/blocks/block-coauthor-name/edit.js
  src/blocks/block-coauthor-name/index.js
  src/blocks/block-coauthors/block.json
  src/blocks/block-coauthors/components/memoized-coauthor-template-block-preview.js
  src/blocks/block-coauthors/edit.js
  src/blocks/block-coauthors/index.js
  src/blocks/block-coauthors/save.js
  src/blocks/block-coauthors/style.css
  src/blocks/components/placeholder-image.jsx
  webpack.config.js
Labels: Type: enhancement, Status: needs testing

#1038 Fix missing author column in wp-admin Posts table
  php/class-coauthors-plus.php
Labels: Status: needs review

#1034 Fix PHP version 7.4 requirement
  .github/workflows/integrate.yml
  README.md
  composer.json
  php/api/endpoints/class-coauthors-controller.php
  php/blocks/block-coauthor-avatar/class-block-coauthor-avatar.php
  php/blocks/class-blocks.php
  php/class-coauthors-endpoint.php
  php/class-coauthors-guest-authors.php
  php/class-coauthors-iterator.php
  php/class-coauthors-plus.php
  php/class-coauthors-template-filters.php
  php/class-coauthors-wp-list-table.php
  php/class-wp-cli.php
  php/integrations/yoast.php
  php/integrations/yoast/class-coauthor.php
  tests/Behat/FeatureContext.php
  tests/Integration/AuthorQueriedObjectTest.php
  tests/Integration/AuthorQueriesTest.php
  tests/Integration/CoAuthorsPlusTest.php
  tests/Integration/EndpointsTest.php
  tests/Integration/GuestAuthorsTest.php
  tests/Integration/ManageCoAuthorsTest.php
  tests/Integration/TemplateTags/CoauthorsGetAvatarTest.php
  tests/Integration/TemplateTags/CoauthorsPostsLinksSingleTest.php
  tests/Integration/TemplateTags/CoauthorsPostsLinksTest.php
  tests/Integration/TemplateTags/CoauthorsWpListAuthorsTest.php
  tests/Integration/TemplateTags/GetCoauthorsTest.php
  tests/Integration/TemplateTags/IsCoauthorForPostTest.php
  tests/Integration/TemplateTagsTest.php
  tests/Integration/bootstrap.php
Labels: Status: needs review, Type: maintenance

#1035 Increase minimum WordPress version to 5.9
  .github/workflows/integrate.yml
  co-authors-plus.php
  composer.json
Labels: Type: maintenance
