Repository Automattic/Co-Authors-Plus, pull requests merged in 2025-03, with the labels that each got.

#1104 Increase composer/installers version
  composer.json
Labels: Type: maintenance

#1105 Add SVN install to integrate workflow
  .github/workflows/integrate.yml
Labels: Type: maintenance

#1103 Protect against pattern edits
  php/class-coauthors-endpoint.php
  tests/Integration/EndpointsTest.php
Labels: Type: bug

#1107 Tidy-up CHANGELOG for 3.6.4
  CHANGELOG.md
Labels: Type: documentation
